### ISSUE TITLE
fail to compile

### ISSUE THREAD

**Issue by incloudmanager** [aliyun-beta/aliyun-jclouds#1]
When I use mvn to compile ,it go to wrong. below is the log

警告: 没有处理程序要使用以下任何注释: com.google.inject.ImplementedBy,javax.inject.Named,com.google.inject.Provides,org.jclouds.collect.Memoized,javax.annotation.Resource,org.jclouds.location.Provider,javax.inject.Inject,javax.inject.Singleton
错误: An unhandled exception was thrown by the Error Prone static analysis plugin.
  Please report this at https://github.com/google/error-prone/issues/new and include the following:

  error-prone version: 2.0.5
  Stack Trace:
  java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/incloudos/workspace/aliyun-jclouds/aliyun-slb/src/main/java/org/apache/jclouds/slb/loadbalancer/functions/RegionToLocation.java
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at java.nio.file.Paths.get(Paths.java:84)
        at com.google.errorprone.bugpatterns.PackageLocation.getFilePath(PackageLocation.java:77)
        at com.google.errorprone.bugpatterns.PackageLocation.matchCompilationUnit(PackageLocation.java:58)
        at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:594)
        at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:142)
        at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:563)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:53)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:70)
        at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:45)
        at com.google.errorprone.ErrorProneAnalyzer.reportReadyForAnalysis(ErrorProneAnalyzer.java:151)
        at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:115)
        at com.google.errorprone.ErrorProneJavacJavaCompiler.postFlow(ErrorProneJavacJavaCompiler.java:123)
        at com.google.errorprone.ErrorProneJavacJavaCompiler.flow(ErrorProneJavacJavaCompiler.java:97)
        at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1262)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:859)
        at com.sun.tools.javac.main.Main.compile(Main.java:249)
        at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:249)
        at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:159)
        at com.google.errorprone.ErrorProneCompiler.compile(ErrorProneCompiler.java:88)
        at org.codehaus.plexus.compiler.javac.errorprone.JavacCompilerWithErrorProne$CompilerInvoker.compile(JavacCompilerWithErrorProne.java:219)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.compiler.javac.errorprone.JavacCompilerWithErrorProne.performCompile(JavacCompilerWithErrorProne.java:91)
        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:785)
        at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
1 个错误
1 个警告
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

**Comment by anyways** [comment]
参见[fix issues#1](https://github.com/aliyun-beta/aliyun-jclouds/pull/2)
